memcache:
  host: "172.18.0.21"
  port: 11211

redis:
  host: "172.18.0.21"
  port: 6379
  password: "redis_passwd"

db:
  type: "mysql"
  host: "172.18.0.21"
  username: "root"
  password: "123456"

prometheus:
  prometheus_url: "http://172.18.0.21:9090"
  prometheus_cfg_path: "/root/xwh/prometheus/prometheus.yml"

operation_service_api:
  listen_port: 11011
  log_dir: "/var/operation_service_x"



file_service:
  listen_port: 11001
  cache_dir: "/var/operation_cache"


